import type { Metadata } from "next";
import { SiteHeader } from "@/components/site-header";
import Providers from "@/lib/providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function TemplateLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <Providers>
        <SiteHeader />
        {children}
      </Providers>
    </>
  );
}
